### ISSUE TITLE
Time in Grade - Humanize Display

### ISSUE THREAD

**Issue by mattgwagner** [mattgwagner/Battery-Commander#101]
Right now it's in days, not useful when it can scope out to years and that's what we usually go by.

**Comment by erichmccartney** [comment]
consider adding color scheme for meeting TIG for a particular grade.  say grey until TIG is met then green?

**Comment by erichmccartney** [comment]
the same color scheme could be applied to education level.  This way all greens across the page indicates eligible for promotion, or is that too many colors?

**Comment by mattgwagner** [comment]
That's logical -- I'm going to move this to a separate ticket to collect the regs on it.
