### ISSUE TITLE
Alert Roster

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#140]
Thoughts on integrating a basic alert roster: say email and phone only? Future uses could be uses could avoid that mass emailing of orders that Alma just did.

**Comment by mattgwagner** [comment]
Be able to send an SMS to a group (all?) in a unit and have an endpoint to receive responses, aggregate them.

**Comment by mattgwagner** [comment]
For this, I am planning to make this a separate app that can integrate with the BC app, RE: [Alert Roster](https://github.com/mattgwagner/alert-roster). This gives me greater flexibility and can address a need I've seen in TDY situations where we want to stand up a distro but explaining and configuring GroupMe might be out of scope.

**Comment by mattgwagner** [comment]
Closing this to be tracked in the other repository as work progresses.
