### ISSUE TITLE
Evaluation detail edit

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#160]
error when editing dates of evaluation, won't save.  Also hide previously input sr rater data
![image](https://user-images.githubusercontent.com/29133992/28494662-d6933f74-6f02-11e7-9b6c-3738d5363857.png)

**Comment by mattgwagner** [comment]
Error was caused by some bad logic that only returned E1-E4 in the drop down list, which didn'tinclude the previous rater/senior rater. THe error message itself indicates that the relationship to the rater/senior rater didn't exist. Need to also fix the error message.
