### ISSUE TITLE
Rank - Missing MSG

### ISSUE THREAD

**Issue by mattgwagner** [mattgwagner/Battery-Commander#168]
We have the E8 1SG rank but not MSG. Cadet is shoved in there, and the increments are such that we can't add it in unless we remove Cadet, move anyone existing in the Db to the new identifier (-1?), and then add it with the same id.

**Comment by mattgwagner** [comment]
Couldn't use -1, since we're backing the enum with a byte. Cadet is now a 0, and MSG shares an enum with 1SG. Shoved SGM in where Cadet was.

**Comment by erichmccartney** [comment]
read the about and you lost me, but I suppose its worth exploring CPL, WOC, and OCS at the same time?

**Comment by mattgwagner** [comment]
Basically just re-arranged some choices on the Rank selection list. 

CPL could be `Rank.E4` and WOC and OC could fall in with CDT, unless we felt like splitting all of those options out to their own (i.e. MSG and 1SG are the same selection now).

**Comment by erichmccartney** [comment]
the complicated part to me about WOC, OC, and CDT is that they could all be differe E# ranks depending on the situation.

Also with MSG/1SG being the same selection right now I'm sure 1SG will have something to say when his name appears as MSG/1SG

**Comment by mattgwagner** [comment]
Part of the difficulty is that I originally didn't space ranks out so that I could do things like `if Soldier.Rank > Rank.E7` but if I'd have to move a bunch of data if I went back and shove new ranks in there.
