### ISSUE TITLE
Delete button "are you sure" or undo 

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#171]
I deleted an evaluation today while being click happy. Any way to add and "are you sure" pop up or even cooler would be a Google like undo near the bottom of the page that lingers for a few seconds after transactions

**Comment by mattgwagner** [comment]
Closing #117 as a dupe.

**Comment by mattgwagner** [comment]
It's much easier to have a delete confirmation, code-wise, so that will probably be the 80% solution.

**Comment by mattgwagner** [comment]
![image](https://user-images.githubusercontent.com/157644/28991764-3a58576c-795b-11e7-8f0b-bec4b22f8f76.png)
