### ISSUE TITLE
Apply Time Considerations to APFT, ABCP Results

### ISSUE THREAD

**Issue by mattgwagner** [mattgwagner/Battery-Commander#189]
Similar to DSCA and IWQ, APFT and ABCP results "age out" and are no longer applicable after a certain period of time. They can probably be considered non-tested after a set period of time (1 year?).

/cc: @erichmccartney

**Comment by erichmccartney** [comment]
realized this weekend that ABCP is actually semi-annual, therefore the color sequence should be (or similar):
Green: 0-6 mos
Amber: 6-9 mos
Red: 9-12 mos
