### ISSUE TITLE
Vehicle Driver/A-Driver -- Un-assign from Other Vehicle if Added to New One

### ISSUE THREAD

**Issue by mattgwagner** [mattgwagner/Battery-Commander#194]
If a driver is assigned to another vehicle, remove them from it when assigning them to a new one.

**Comment by erichmccartney** [comment]
this works by position only.  Meaning I could assign the same person to both driver and a driver but not the driver or a driver in two vehicles.  This is really turning into a monster.  how do you have it set, do these lists pull all people? or just from the unit selected?

**Comment by mattgwagner** [comment]
Ahh, good catch, definitely an oversight. Also, it pulls all people currently for simplicity -- it wouldn't be too hard in the future to filter lists by the assigned unit.

RE: https://github.com/mattgwagner/Battery-Commander/blob/master/Battery-Commander.Web/Controllers/VehiclesController.cs#L144

**Comment by mattgwagner** [comment]
Fixed this as well, @erichmccartney 

It needs to be re-worked once it supports passengers, but at least is logical now.
