### ISSUE TITLE
Vehicle Nomenclature - Turn into Enum

### ISSUE THREAD

**Issue by mattgwagner** [mattgwagner/Battery-Commander#195]
There's a certain set of known vehicle 'nomenclature', turn it into an enum rather than a free-text field.

i.e. M1097, M1083, etc.

/cc: @erichmccartney can you give me a general list that makes sense?

**Comment by erichmccartney** [comment]
We could pull a list of all that we have in the BN. But invariably they will change and A1, A2 suffixes will be added over time. Could it be a drop down with the option to add? I know SharePoint as a feature like that

**Comment by mattgwagner** [comment]
For now, just going to leave this as free-text, since it would require maintenance and have little value-add.

**Comment by mattgwagner** [comment]
This is being migrated to [redlegdev/Redleg.app](https://github.com/RedLegDev/RedLeg.app)
