### ISSUE TITLE
Fix PERSTAT - Swap Columns, Make Numbers Clickable

### ISSUE THREAD

**Issue by mattgwagner** [mattgwagner/Battery-Commander#205]
The enlisted and warrant officer columns have reversed data. Also, use the numbers as links to the /Soldiers raw data filtered by the status.

![image](https://user-images.githubusercontent.com/157644/31393464-c47e0e82-ada9-11e7-9449-ca2ee6107143.png)

**Comment by mattgwagner** [comment]
/cc: @erichmccartney should be good to go now. A few fields aren't links, since I don't track them as statuses in the system... i.e. KIA, WIA, MIA, or the warrant officer ranks.

**Comment by erichmccartney** [comment]
looks good.  excepted I added an SM today and the increase isn't reflected in the PERSTAT

**Comment by mattgwagner** [comment]
I deployed a few fixes the past 15 minutes -- it was because my logic was jacked up for the Enlisted column... forgot to include NCOs... make IsEnlisted just refer to all non-Officers for now.
