### ISSUE TITLE
CLS - Color Coding

### ISSUE THREAD

**Issue by mattgwagner** [mattgwagner/Battery-Commander#209]
this came up recently at BN as a desire to roll up. definitely a good addition if it can be added with a green, amber, red status with associated timelines that I don't know off the top of my head.

**Comment by mattgwagner** [comment]
/cc: @erichmccartney -- When I glanced at this during original coding (not a deep dive), Wikipedia includes a citation indicating the following:

"While a CLS certification is technically permanent, soldiers in Priority 1 units (actively-deploying brigade combat teams, for example) must retake the course once a year to retain their certification.[2]"

http://www.me.ngb.army.mil/units/rti/resources/IS0871_Edition_C_ALMS.pdf

**Comment by mattgwagner** [comment]
@erichmccartney so the way I currently handle this is if they have a CLS date within the past year, they show up as GO / green.

If they have a CLS date, but it's over a year, they get a (Due) / amber. 

If they do not have a date, no indicator is shown.

Thoughts on meeting the intent?

**Comment by erichmccartney** [comment]
sounds right to me
