### ISSUE TITLE
Cadet SSD/Edu

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#210]
Now that we have a CDT some special concerns arise with SSD/Edu status.  Currently, the CDT is shown on the SSD report, they should be left off same as officers are.  And currently for EDU, they appear to be left off, can we add them to this with a requirement of "CST" which replaces the legacy LDAC course and is the significant event that transitions them from junior to senior cadets.

**Comment by mattgwagner** [comment]
While I'm re-jiggering the Cadet handling, do they fall in with the Officers or Enlisted on the PERSTAT? Right now, they're in the Enlisted category, which is why they also roll up in the SSD status tracking.

**Comment by mattgwagner** [comment]
Removed SSD requirement via 574b1f1f964c95636b64d13dc65e33abec3fabc3

**Comment by erichmccartney** [comment]
could the CDT sort to between 1SG and 2LT on the edu tab

**Comment by mattgwagner** [comment]
Similar comment to other on 1SG/MSG ranks -- they're ordered by the backing value, and CDT is now 0. Might have to do a data migration then.
