### ISSUE TITLE
Name Drop Down Type and auto complete 

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#215]
In various locations there are drop downs for names, as this grows it is becoming tedious to scroll to a name is it possible to start typing a name and have a shorter list appear?

**Comment by mattgwagner** [comment]
Hmm, I used to have this hooked up to most of the select lists, I think I had to make it opt-in because it was breaking the modals used for updating drivers on the vehicle manifest. I'll check it out.

**Comment by mattgwagner** [comment]
The only soldier list that I found in the code that didn't have the attribute was the Supervisor list on the Soldier edit screen. If you find any other that were bothering you, call them out and I'll re-open.

/cc: @erichmccartney

**Comment by erichmccartney** [comment]
So the search only works off the first letter? ie. "C" for CPT?  I guess I should have explained better, could we type any part of a name to have the field work more as a search? ie. type "matt" and get all the matt's to select from? If thats crazy the way it is works

**Comment by mattgwagner** [comment]
Disregard, I tested on the live site and it doesn't look like it's working any more. I wonder if an upstream library changed? It used to search anything visible in the list.

**Comment by mattgwagner** [comment]
/cc: @erichmccartney OK no for real, fixed it this time.

**Comment by erichmccartney** [comment]
works great

**Comment by erichmccartney** [comment]
looks like the driver and A. driver drop downs didn't get the search treatment

**Comment by mattgwagner** [comment]
Unfortunately, those were the original two (on the modal update for drivers) that broke and made me have to selectively enable the dropdrown list searching. Something to do with being opened that way. Will open a separate issue.
