### ISSUE TITLE
Vehicle Manifest - Manage Passengers

### ISSUE THREAD

**Issue by mattgwagner** [mattgwagner/Battery-Commander#216]

**Comment by erichmccartney** [comment]
I noticed the seat count only counts seats if the following is true: Status-FMC and Location-HS.  That makes sense to me.  However, the option to place someone in that vehicle remains.

**Comment by mattgwagner** [comment]
Updated the vehicle model to include "troop capacity", thus "total capacity" equals seats +troop capacity.
