### ISSUE TITLE
Vehicle Manifest - location field

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#225]
Can't remember if we talked about this. But if I get Smith in here this function would be vastly useful to him and probably us as well. 

Include vehicle location field. Consider the following options: HS, FSC, FMS, CSMS, MATES and Other. With a default to HS. Not sure if this needs any color. If it could effect our avaliable seat count, ie a vehicle could he FMC but at FMS and thus not avaliable to us so the seats shouldn't count. Priority for view would be just before notes, not sure about that however.

**Comment by mattgwagner** [comment]
Makes sense -- I can make the location either an enum (hard-coded choices) or look-up (database configurable options). Enum, as mentioned previously, is fairly simple.

**Comment by erichmccartney** [comment]
I recall you says that you have a preference for the hard code. I agree with that since the other category can cover alot in conjunction with the notes field and if we need an additional option later we put in a ticket. So I suppose other would make the vehicle in avaliable to us as well.

**Comment by mattgwagner** [comment]
I do -- the code is easy enough to change and deploy to add options, but supporting the look-up from the database means several other pieces to build and manage.

**Comment by mattgwagner** [comment]
@erichmccartney can you confirm a spelled-out version of each?

- HS Home Station
- FSC Forward Support Company
- FMS Field Maintenance Shop
- CSMS Combined Support Maintenance Shop
- MATES Maneuver Area Training Site

**Comment by erichmccartney** [comment]
Confirm all

**Comment by mattgwagner** [comment]
@erichmccartney I added the field. 

I will need to revisit the calculated pieces for 'on-hand' and 'seats' as you mentioned above, will probably have some questions to clarify. 

Also, probably will end up with abbreviations and colored labels to match the rest of the list.

**Comment by erichmccartney** [comment]
I mislead you MATES = Maneuver Area Training Equipment Site.  Field looks good does an "other" option make sense to you?

**Comment by erichmccartney** [comment]
also could the field work like FMC/NMC field? click to change and also modify note?

**Comment by mattgwagner** [comment]
Whoops, left off the 'E' when pasting it over, the app already had it right. 

Added 'Other'. 

Also added it to the update modal dialog.

**Comment by mattgwagner** [comment]
Need to tweak it so that the current location is selected in the modal, not currently working.
