### ISSUE TITLE
Evaluation workflow error 

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#229]
Eval id 1428385. Has fatal error when returning to rater.

**Comment by mattgwagner** [comment]
![image](https://user-images.githubusercontent.com/157644/32008506-56b5a20c-b97a-11e7-8e1b-311f6ede811d.png)

**Comment by mattgwagner** [comment]
@erichmccartney this should be fixed and on the site in a few minutes.
