### ISSUE TITLE
Quick Count at top

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#230]
Change the count logic to be similar the vehicle tracker.  

Delinquent: # >60days past due
Due: # Thru date passed
Next 30: # due within 30 days
Next 60: # due within 60 days
Next 90: # due within 90 days

![image](https://user-images.githubusercontent.com/29133992/32135170-9e5c4890-bbc8-11e7-8dd3-2633eebf5e39.png)
![image](https://user-images.githubusercontent.com/29133992/32135174-b23f77ec-bbc8-11e7-88d8-2e77b78f44f2.png)

**Comment by mattgwagner** [comment]
The UI leaves something to be desired, but at least surfacing the data. 

![image](https://user-images.githubusercontent.com/157644/32144904-7766671a-bc96-11e7-9d6e-a8c59b294f52.png)

**Comment by mattgwagner** [comment]
I feel like this could also go on the unit rollup reports, along with the vehicle one.

**Comment by erichmccartney** [comment]
looks great except the count doesn't appear correct, as we only have 2 evals due in the next 30 days

**Comment by mattgwagner** [comment]
Absolutely right, I inverted the conditions to group those up.

**Comment by mattgwagner** [comment]
@erichmccartney clarifying... should the "Within 60" include ones within 30? Or is it only ones between 30 and 60?

**Comment by mattgwagner** [comment]
Updated to 30 < x <= 60, etc.

**Comment by mattgwagner** [comment]
![image](https://user-images.githubusercontent.com/157644/32146292-49c6242a-bcab-11e7-82d3-fdce2655ae09.png)
