### ISSUE TITLE
Small Screen View Ranking

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#231]
Specifically, on smaller screens I'm thinking the most valuable fields are:

1- Rated SM: is it possible to only show Ranks Last Name? (and maybe first initial?)
2- Delinquency
3- Action Due: Potential new field that pulls the Name of the person corresponding with the work flow (SM, rater, Sr rater, etc)

The details field should be in the "+" as all it does is take up screen space

**Comment by mattgwagner** [comment]
I am using a helper to display the rater soldier which is used elsewhere, which is the RANK LAST FIRST in one column. I can pull it out and have it match closer to the SOLDIERS list.

Right now, priority is Ratee, Delinquency, Status, et al.

I will check into something along the lines of `Action Due`.

**Comment by erichmccartney** [comment]
Not sure if this is just my phone but this is what I am trying to solve. The mobile view is kinda worthless.  And will names being so long even in landscape view its difficult to extract useful info.
![screenshot_20171029-095305](https://user-images.githubusercontent.com/29133992/32144443-4f4eb2de-bc8f-11e7-93cc-a62e7eb8f119.png)

**Comment by mattgwagner** [comment]
Ah, yeah, definitely not terribly useful. I need to get in a better habit of testing things using mobile-compatible modes, since that's probably a more common use case for this app anyway.

**Comment by mattgwagner** [comment]
OK, I was able to reproduce this in Chrome when set as a Galaxy S5, so definitely something I need to look at.

![image](https://user-images.githubusercontent.com/157644/32144917-c832a640-bc96-11e7-845d-afb82f827927.png)

**Comment by mattgwagner** [comment]
I can continue to tweak if desired, but this is what it'll look like on a Galaxy S5 for now. Marginal improvement?

![image](https://user-images.githubusercontent.com/157644/32144969-775fee8e-bc97-11e7-8855-e5432dc8f805.png)

**Comment by erichmccartney** [comment]
nice.  is it possible to drop the word "details" and just have that "+" sign?

**Comment by mattgwagner** [comment]
I think I had to have it there previously because otherwise that column got chopped off on small screen, and thus you wouldn't ever get to the eval details. I'll play with it some more.

**Comment by mattgwagner** [comment]
Calling this one closed for now, I think this is about as optimal as I can get.

![image](https://user-images.githubusercontent.com/157644/32356820-1f105a5a-c00e-11e7-8e50-f1ac192ea4b8.png)
