### ISSUE TITLE
Quick Count FMC@HS

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#233]
The logic for FMC count appears to be only if the vehicle is at HS, which makes sense, but we should probably call that out: "FMS @HS: ##" instead of "FMS: ##"  in the below example there were 13 FMC vehicles however only 12 at HS
![image](https://user-images.githubusercontent.com/29133992/32135378-441965b2-bbcc-11e7-86c9-a76624681736.png)

**Comment by mattgwagner** [comment]
Fixed, thanks!
