### ISSUE TITLE
Cost Estimate Worksheet (CEW)

### ISSUE THREAD

**Issue by mattgwagner** [mattgwagner/Battery-Commander#237]
Need to provide more details and example. For Readiness Office.

Missing Pieces:
- MOS (See #29)
- M-Day / AGR / ADOS Status

On the spreadsheet, I can't tell yet which are keyed values from other sources or I can pull from the BC app.

**Comment by erichmccartney** [comment]
Maybe worth adding this attribute as we've seen scenarios that rely on this data, namely SAD.  Status Field: M-DAY / AGR / ADOS / TECH

There is really quite a bit going on in that sheet.  Paytable, BAH, and per diem are all hosted on the DFAS site with combinations of information from each SM.  I guess the question is can you pull from that?  If not I would think that the only table worth importing would be the paytable as the others are terribly large.

**Comment by mattgwagner** [comment]
This seems like it's nothing something I'm interested in taking on.
