### ISSUE TITLE
SSD Report Links Broken

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#239]
Links from the SSD rollup report don't show the filter list of SMs, instead a complete roster is displayed.  Whereas clicking a #2 only two SM should be displayed.

![image](https://user-images.githubusercontent.com/29133992/32246774-84865e16-be56-11e7-8c1a-529978c37d3f.png)

**Comment by mattgwagner** [comment]
Good catch -- I updated all of the links on all of the unit breakdown tables.

**Comment by erichmccartney** [comment]
Multiple broken links, SGT incomplete, all totals, to name a few

**Comment by mattgwagner** [comment]
Gah, trying to work too quick, didn't check an update elsewhere that broke it.
