### ISSUE TITLE
Investigate Embedding Data into Excel, PowerPoint from API

### ISSUE THREAD

**Issue by mattgwagner** [mattgwagner/Battery-Commander#246]
You can link Excel sheets to API web calls (static API token?)... and then use those sheets to power graphs in PowerPoint decks... this would be crazy useful if we could produce a simple way to update the charts in Battalion Training Meeting slide decks?

/cc: @erichmccartney

**Comment by erichmccartney** [comment]
BN is probably a pipe dream but our Btry meeting slide deck is a reality

**Comment by mattgwagner** [comment]
https://developers.google.com/slides/how-tos/add-chart
