### ISSUE TITLE
ABCP Measurements in Large View?

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#251]
Is it possible to include the measurements in a large view?  I think this would help in doing compliance checks instead of having to view the detail on every SM.  I do like how on ABCP and APFT you click on the GO or NOGO to view the details.

**Comment by mattgwagner** [comment]
![image](https://user-images.githubusercontent.com/157644/32473898-ca230b50-c337-11e7-8fd6-3ad474fa8db3.png)
