### ISSUE TITLE
Unable to update SSD on  Mobile device

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#252]

**Comment by mattgwagner** [comment]
This is a side-effect of the responsive datatables -- the columns get re-written so they no longer have the same interaction hooks. Not sure how to tackle this outside of re-writing the whole bit.

**Comment by mattgwagner** [comment]
I'm going to close this -- I don't plan on making updates to the SSD page, since it hasn't been used in over a year.
