### ISSUE TITLE
Perstat Reset Button

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#253]
I think a perstat reset may be useful similar to what you created on the vehicle manifest.  me sure to include a "are your sure?" prompt

**Comment by mattgwagner** [comment]
What should I reset all of the statuses to be? Reference options below:

https://github.com/mattgwagner/Battery-Commander/blob/master/Battery-Commander.Web/Models/Soldier.cs#L97

**Comment by erichmccartney** [comment]
I think the "?" makes the most sense as when we arrive at a training assembly or activation we really don't know if they will show.

**Comment by mattgwagner** [comment]
Makes sense. The UX for setting a status probably needs some love, since the click -> modal -> save -> refresh is time-intensive for updating a chunk of SMs at once.

**Comment by mattgwagner** [comment]
![image](https://user-images.githubusercontent.com/157644/33155985-59dcadea-cfc3-11e7-8959-e7ec188b57b9.png)

![image](https://user-images.githubusercontent.com/157644/33155990-6253832c-cfc3-11e7-828e-7b2bdd596780.png)

/cc: @erichmccartney
