### ISSUE TITLE
ABCP Cheatsheet

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#254]
What if we added the graphical images from the manual to the input screen.  this would allow the SM inputting the data to also view the correct measuring techniques while observing the execution.  This is especially important as we don't do this every day. and maybe even some key excerpts.
![image](https://user-images.githubusercontent.com/29133992/32452565-e4d95f08-c2e7-11e7-9b9b-0dd7d4dce8af.png)
![image](https://user-images.githubusercontent.com/29133992/32452581-f420ced8-c2e7-11e7-9e06-5eaf78893738.png)

**Comment by mattgwagner** [comment]
I like it -- make it as dummy-proof to follow the process as possible.

**Comment by mattgwagner** [comment]
Not perfect, but the image is responsive and will scale with the size of the screen and provide an instant reference.

![image](https://user-images.githubusercontent.com/157644/39337829-1da42620-498d-11e8-9db8-1973abc9e512.png)

/cc: @erichmccartney

**Comment by erichmccartney** [comment]
this looks great, I assume the picture is different for females?

**Comment by mattgwagner** [comment]
Correct; it looks at the gender of the Soldier being measured and toggles the images... it actually let me reference the images directly from your upload so it was just adding one HTML tag.
