### ISSUE TITLE
ABCP Measurement Validation

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#255]
create validation errors with pop up guidance to forbid measurements that exceed standards.  This is why I was wanting to see all measurements on one screen to quickly identify compliance errors, namely circumference measurements that are greater than 1-inch apart.

**Comment by mattgwagner** [comment]
Logical -- I had this in the backlog, makes sense.

**Comment by mattgwagner** [comment]
![image](https://user-images.githubusercontent.com/157644/32816394-749114f2-c986-11e7-9795-7227f3c56de3.png)

**Comment by mattgwagner** [comment]
Also, on the ABCP list. Not good looking, but shouldn't be a common, long-lasting scenario:

![image](https://user-images.githubusercontent.com/157644/32816496-f79fa7dc-c986-11e7-867a-e7659bac7954.png)

**Comment by erichmccartney** [comment]
Had someone enter waist measurements that were 1 inch different the app accepted the entry and call them a "NO GO" took a second to realize we changed it so all measurements were the same and it became a "GO."

Is it possible to not accept the entry, and highlight the field(s) with errors? or if the entry is accepted then not provide a "GO" or "NO GO" since the measurements are invalid.
