### ISSUE TITLE
APFT - Stacked Line Chart?

### ISSUE THREAD

**Issue by mattgwagner** [mattgwagner/Battery-Commander#259]
Might be cool to switch the chart for APFT to show how the different scores combine to make the total, i.e. from:

![image](https://user-images.githubusercontent.com/157644/32474603-586e871a-c33b-11e7-8cf8-7ede2f781608.png)

![image](https://user-images.githubusercontent.com/157644/32474631-76a7728c-c33b-11e7-8f36-66a8d45beaa8.png)

**Comment by erichmccartney** [comment]
I like it

**Comment by mattgwagner** [comment]
![image](https://user-images.githubusercontent.com/157644/32814739-48ace27e-c97e-11e7-8daf-0cf77298c6a0.png)
