### ISSUE TITLE
iCal Feed for Unit Events

### ISSUE THREAD

**Issue by mattgwagner** [mattgwagner/Battery-Commander#265]
For those of us who love the visual representation of a calendar...

Provide a (unit-specific?) iCal feed that can be subscribed to from Outlook/Google Calendar containing:

- [x] Soldier ETS Dates
- [x] Soldier Birthdays (see #134)
- [x] Evaluations Thru/Due Dates
- [x] API Key Management
- [x] Expose Link to Calendar Feed in UI

/cc: @erichmccartney

**Comment by erichmccartney** [comment]
Interesting as long as it's not a public iCal I say go for it.

**Comment by mattgwagner** [comment]
Google Calendar has a similar pattern wherein you can publish 'private' feeds, which embeds a very long, non-guessable key into the URL, so that it doesn't require additional permissions. You can then reset the URL if you feel it's no longer private or want to reset sharing. I use a similar pattern in another hobby app to publish my expenses/bills into my Google Calendar.

**Comment by erichmccartney** [comment]
Yup what I want thinking. Understood

**Comment by mattgwagner** [comment]
Right-click, Copy Link Address:

![image](https://user-images.githubusercontent.com/157644/34473069-024a6cd2-ef3c-11e7-9539-0a38a6896dad.png)

Use Add "From URL" in Google Calendar:

![image](https://user-images.githubusercontent.com/157644/34473078-21083e7e-ef3c-11e7-8abf-7b0c39f395cb.png)

**Comment by erichmccartney** [comment]
nice work.  so I had to right click the "Calendar Feed" link and copy the url since left click initiated a download, was that your intent?

Interesting how there is an event almost every other day...overwhelming for a part-time job huh.

I wonder if this could be iframed into GKO SP site?

**Comment by mattgwagner** [comment]
RE: Right-click, yep, that was the short-term in the instructions above while I figure out a better way to connect things.

If you add this to your Google Calendar, you can then generate HTML to embed into other pages and pick other calendars to display as well...i.e. embed this + the unit maintained calendar in one displayable piece.
