### ISSUE TITLE
Dropdown Tab

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#266]
In the drop down fields it would be helpful if when typing and the option becomes auto selected thay tab could be hit and that item is selected and the cursor is moved to the next field.

Not sure if I explained that well but lots of web forms operate like that

**Comment by mattgwagner** [comment]
Good call; fixed. All it took was a configuration parameter on the library I use for the searchable select lists.

**Comment by erichmccartney** [comment]
That easy huh. It was driving me nuts and I kept forgetting to put to a ticket in
