### ISSUE TITLE
SSD E8

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#289]
After continued red tap and ridiculousness I think its more appropriate to make SSD4 the requirement for E8s (vice SSD5)and not require SSD5 until the grade of E9 is reached.  E8 cannot be enrolled in SSD5 till they make the E9 list, which could be never.

**Comment by mattgwagner** [comment]
Deploying the change for this now -- since it never hit us, I didn't have it coded for E9, which I also added while I was in there.
