### ISSUE TITLE
Fix CPL Requirements

### ISSUE THREAD

**Issue by mattgwagner** [mattgwagner/Battery-Commander#304]
SSD: CPL is required SSD1
NCOES: CPL Is required AIT
NCOER: no evaluation required.

/cc: @erichmccartney

**Comment by mattgwagner** [comment]
@erichmccartney are there any differing requirements that you know of for MSG vs 1SG? I didn't think so, but wanted to hit that while I was in there.

**Comment by erichmccartney** [comment]
MSG and 1SG have the same requirements
