### ISSUE TITLE
Weekly Eval Email - Include Days Due

### ISSUE THREAD

**Issue by mattgwagner** [mattgwagner/Battery-Commander#331]

**Comment by erichmccartney** [comment]
Nice touch.  However, a more robust table would be nice so 1SG could just forward to the CSM. I'll have him forward that to you. 

A question does it only sent to people listed on the duelist? If so great, but would also want to include the XO, CDR, RNCO, 1SG regardless if they are involved in the due evaluation

**Comment by mattgwagner** [comment]
@erichmccartney as mentioned separately, the logic for this grabs all SM's E-7+ and uses them if they have a personal email address sent, which should (in theory) hit the folks you just mentioned. I'd be interested in a refined format since this is one I slapped together to test out the concept.

**Comment by mattgwagner** [comment]
I switched the evals email over to an HTML template and CC'd all E6+, which makes adding/changing content much easier. I addressed the item in this ticket; I will close it and reopen another regarding @erichmccartney's 1SG request
