### ISSUE TITLE
ERP Updating after EES workflow

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#356]
Since DPRO is fed by either SIDPERS and/or SIBx and EES talked to none of those 3, its the job of typically the RNCO or ANCO to update SIDPERS and/or SIBx once an evalution is submitted.  Perhaps send a email to that person once the eval is submitted, so they can update it.  Ultimatley units are judged based on a DRPO export, it would be nice to have that clean as possible

**Comment by mattgwagner** [comment]
This makes sense; I originally intended to have the steps trigger actions in the workflow, but instead just went to the simpler "email people involved". I think the missing link here would be having a place to identify which SMs to notify on this action, i.e. who is the unit ANCO/RNCO.

**Comment by mattgwagner** [comment]
This may be migrated to https://github.com/RedLegDev/WriteMyNCOER.com
