### ISSUE TITLE
CLS Cert/ReCert Timeline Tracking

### ISSUE THREAD

**Issue by mattgwagner** [mattgwagner/Battery-Commander#36]

**Comment by erichmccartney** [comment]
this came up recently at BN as a desire to roll up.  definitely a good addition if it can be added with a green, amber, red status with associated timelines that I don't know off the top of my head.

Leads me to another thought, what about a reference tab that links to regulations which we pull from similar to what you did on the ABCP and APFT modules.

**Comment by mattgwagner** [comment]
Added a link to the requirements awhile back, but it's not nearly as cut and dry as other requirements (i.e. APFT, IWQ, etc.)
