### ISSUE TITLE
Weekly Eval Email - Ball In Court

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#364]
Consider adding another column showing the ball in court showing workflow status, ie. rater, sr, reviewer, signature, awaiting submission etc.  Or even bold the rater or sr if its on them since their name is in the body of email.

On that same note if an evals hasn't been updated in 30 days can the font be colored red, to draw attention.

...can't help myself

**Comment by mattgwagner** [comment]
Right now, the emails are batched by unit (partially because I'm limited to 100 per day on the free plan), so I can't bold the recipient at this point but might be a good idea long-term.

I made the row background red (haven't tested how it looks) if not updated in last 30 and the status column.
