### ISSUE TITLE
ABCP BF% Column Visibility 

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#378]

**Comment by erichmccartney** [comment]
There is a roster that DTMS or some other system generates that needs to be filled out by hand.  While viewing the ABCP tab almost all the data is shown except for BF%, it is easy to get that by looking at the details fo the test, but it would be faster if you could turn that column on with the "column visibility" tool

**Comment by mattgwagner** [comment]
![image](https://user-images.githubusercontent.com/157644/52566362-94d95380-2dd7-11e9-8fe7-f9f3bbabcb03.png)
