### ISSUE TITLE
SUTA Request Tracker

### ISSUE THREAD

**Issue by mattgwagner** [mattgwagner/Battery-Commander#42]
Who when why approval status

Historical tracking, provides insight into how often a SM requests SUTA. Tracks the make-up dates, calendar overview of dates that SMs are scheduled.

**Comment by mattgwagner** [comment]
Example Form -- Perhaps we can have a digital version of this that doesn't require a login to submit?

![image](https://user-images.githubusercontent.com/157644/27302743-508aac02-5506-11e7-9051-515ff0f1eaf8.png)

**Comment by erichmccartney** [comment]
its a worth endeavor, especially if it routed the approval workflow and our sign-in credentials were the approval, it would be way better than anything we are doing now

**Comment by mattgwagner** [comment]
Considering this one done; all other refinements will be done as separate tasks.
