### ISSUE TITLE
Evaluation Creation Error | SSG J

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#436]
This happened on my phone this weekend and I thought it maybe was a mobile restriction but now I see that I cannot create an evaluation for Jensen.

![image](https://user-images.githubusercontent.com/29133992/67770176-41be3400-fa2c-11e9-974a-7e05f6180b62.png)

**Comment by mattgwagner** [comment]
Hmm, I was just able to create the eval with those same inputs. Something in the validation was off -- I wonder if he wasn't listed as in a unit or something?

**Comment by erichmccartney** [comment]
still getting same the error? idk this one has me stumped.
![image](https://user-images.githubusercontent.com/29133992/67904543-082d1c00-fb45-11e9-8576-b469e27c64d3.png)

**Comment by mattgwagner** [comment]
I ran into this myself today -- I temporarily commented out the validation piece. Will investigate more, but you should be able to create again.

**Comment by mattgwagner** [comment]
Killing this -- just not going to dig too far.
