### ISSUE TITLE
Instructions / Scoring Matrix

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#437]
While attempting to get usage of this app from an infantryman cpt, questions about the pt manual kept coming up, clearly, he didn't prepare well, LTs tend to act the same way, in my experience.  During this, I noticed that currently, the link to the FM is only displayed when viewing the details of an individual record. Also army pubs has appeared to have broken the link
![image](https://user-images.githubusercontent.com/29133992/68090331-7ffa8f80-fe40-11e9-811f-da599d453d93.png)

**One solution** could me to place images of the important quick references (instructions, standards, and scoring matrix) on the APFT page.
![image](https://user-images.githubusercontent.com/29133992/68090309-52154b00-fe40-11e9-9a67-9dce4812d527.png)

Another Solution or Additional Place(s) would be to place the APFT references in the main redleg.app library which seemed to only be artillery references and didn't include the myraid of other standard LT type manuals.  Another place to put this would be on the bc app header maybe called "References"

**Comment by mattgwagner** [comment]
APFT scoring no longer relevant.
