### ISSUE TITLE
Support Form (SF) ID Number Field

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#593]
Something I noticed on the OER tracker in 3rd batt is they are monitoring the SF creation and number.  Not something I ever thought to track, but they also don't have any delinquent OERs as a battalion which is impressive.  However, that could be due to the Davis effect.

**Comment by mattgwagner** [comment]
I literally closed #82 yesterday because it didn't seem like something people actually tracked. Hmm.

**Comment by mattgwagner** [comment]
This may be migrated to https://github.com/RedLegDev/WriteMyNCOER.com
