### ISSUE TITLE
Export Roster to Excel

### ISSUE THREAD

**Issue by mattgwagner** [mattgwagner/Battery-Commander#6]
Would be nice to have the ability to export the roster into an Excel format.

**Comment by mattgwagner** [comment]
Is this just for offline viewing? PDF might be easier.

**Comment by erichmccartney** [comment]
the ability to export evaluation status into either pdf or excel will be very useful for 1SG to keep the CSM happy, which will just make things easier for all of us really.

**Comment by mattgwagner** [comment]
https://datatables.net/extensions/buttons/examples/initialisation/export.html

**Comment by mattgwagner** [comment]
Fixed via 8025fbb6a8117a16b3255d167e549ca58c2e23d6

![image](https://user-images.githubusercontent.com/157644/27012285-7e60b45c-4e92-11e7-9c42-7b584a9598dc.png)

**Comment by erichmccartney** [comment]
nice that was quick.  you know this actually came up during dinner last night.  Praino and Medina were discussing software concepts, whats the world coming to.
