### ISSUE TITLE
Contact Export Tool

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#600]
Joining a new battalion has been exhausting for my ocd contact list tendencies.  what if we could export a csv from the bs app that matched google and icloud contact formats

**Comment by mattgwagner** [comment]
Gmail has a CSV - I don't know much about iPhones, does it support vCard format?

https://docs.fileformat.com/email/vcf/

**Comment by erichmccartney** [comment]
icloud is vcard, sadly I have an icloud account for my work iPhone.  i use an app to live sync my contacts between google and apple.

https://macwaretools.com/blog/import-csv-contacts-to-icloud/

**Comment by erichmccartney** [comment]
[google contacts.xlsx](https://github.com/mattgwagner/Battery-Commander/files/5030684/google.contacts.xlsx)

**Comment by mattgwagner** [comment]
Given that, I'd probably go after vCard, checked and Google Contacts allows VCF update.
