### ISSUE TITLE
Auto Add Evaluation Dates

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#645]
The bar at the top of the evaluation page showing which SM don't' have an upcoming eval in the app is great! Especially the part that prefills the rater and dates.

However, the thru date calculation is in error.  Currently, the start and thru date populate as the same day on different years, which would be 366 or 367 days instead of 365 days.

![image](https://user-images.githubusercontent.com/29133992/96373654-fbca1680-113b-11eb-8335-835ac4684e70.png)

**Comment by mattgwagner** [comment]
This is using the `AddYears` logic in C#, https://github.com/mattgwagner/Battery-Commander/blob/main/Battery-Commander.Web/Controllers/EvaluationsController.cs#L97

We could switch it to use `AddDays(365)` if that makes more sense? 

Homework assignment: submit a PR with the change :-)

**Comment by erichmccartney** [comment]
PR created, #646
