### ISSUE TITLE
Eval Reminder Email sending conflicting data

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#655]
Evaluation, https://bc.redleg.app/Evaluations/Details/236 is in a complete status  

https://github.com/mattgwagner/Battery-Commander/blob/093ccaa00d76b4a7eca8e82a7a099d3377373973/Battery-Commander.Web/Models/Evaluation.cs#L20

However, the email shows "At 1SG Review" and includes it on the email

![image](https://user-images.githubusercontent.com/29133992/100921135-208b0b00-34aa-11eb-9ca4-ed4002266ec1.png)

I couldn't debug but I think I followed your architecture from Evaluation.cs, EvaluationsServices.cs, EvaluationsDueReminderJob.cs

**Comment by mattgwagner** [comment]
I've run into this before -- I think I fixed it on another project that uses `FluentScheduler` for it's background jobs. Thanks for reminding me.

**Comment by mattgwagner** [comment]
@erichmccartney I deployed a change on this, we'll take a look next week.
