### ISSUE TITLE
Eval Changed Email Trigger Delay

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#786]
Often I find myself clicking several actions in the eval workflow, each one generates an email. And sometimes on slow connections like in an armory, it takes minutes to do this.

Is there an easy way to a delay that only one update is sent say every 2 or 5 mins opposed to after every change?

Not a big deal if you know how to use your email box but what I've observed with new users is the only feedback they'll give is "What are all these emails?"  Naturally, I resist the urge to say are they in English? you tell me.

**Comment by mattgwagner** [comment]
Yeahhhhh after I got 49 emails today, I can empathize here.

**Comment by erichmccartney** [comment]
also many times we are playing catchup with updates, ie. finding out that an eval with a status of "at rater" has already been submitted to hqda.  currently, this requires ~7ish clicks and page loads.

perhaps we add the submitted to HQDA button to be visible at all times? maybe off to the right in red? even with a confirmation modal?
