### ISSUE TITLE
APFT - DA705 Generation

### ISSUE THREAD

**Issue by mattgwagner** [mattgwagner/Battery-Commander#80]
Should it be just the latest score, the last 4 scores, or fill the entire 8?

What about Body Composition?

**Comment by erichmccartney** [comment]
Just the latest score with ht/at and bf. The only reason for generating a 705 is to complete something for school or promotion packets. I really want to convince the army to make the 705 a single apft form without ABCP. A multi test format is antiquated like before computer antiquated.

**Comment by mattgwagner** [comment]
For reference, DTMS offers the options to generate either the last 8, or last 7 + 1 blank.

**Comment by erichmccartney** [comment]
nice find, if thats the case then this feature isn't needed, just some training for me and FTS
