### ISSUE TITLE
S1 IPPS-A Update Mechanism

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#800]
The current process requires someone (units do different things) to manually update IPPS-A that an eval has been completed. Similar to what is done for APFT/ABCP and DTMS as the system of record.

Completed is defined as "submitted to HQDA" nobody cares if it gets rejected later.

IPPS-A is the system of record for evals and is what feeds all the bad boy reports, in other words, we could be awesome at evals and think we are rockstars only to find out that S1 / Admin folks aren't keeping up with keying in completion to IPPS-A.

We have an opportunity at 3rd to effect this.  Our AGR S1 NCOIC just deployed and the section will be short-staffed for a year. I talked with the interim NCOIC on how this process currently looks.  He said that he alone does all the manual keying for the BN  and he gets random emails of photos of the EES submission screen as validation and then actions when he can. fml.

My initial thought is that a perhaps in addition to the weekly status update email another email is sent to S1 with a list of values that have been 'submitted to HQDA'  Not sure on how to ID S1 folks, maybe an option on their profile? Or if we had MOS haha

I imagine the required data is:

- DODID
- SM
- EES ID
- Thru Date

Of course, then we might need a check box or similar on the eval to indicate that the eval has been keyed to IPPS-A

In a future case, I can investigate if there is a format that enables bulk updates in IPPS-A but the email above is a great start.

**Comment by mattgwagner** [comment]
This may be migrated to https://github.com/RedLegDev/WriteMyNCOER.com
