### ISSUE TITLE
Soldier - Based on Last 'Thru Date' on NCOER, Project Next NCOER Date

### ISSUE THREAD

**Issue by mattgwagner** [mattgwagner/Battery-Commander#89]
Auto-add to list?

**Comment by erichmccartney** [comment]
I agree the Soldier tab could be a due out list, it shows when the SM ets's, when abcp is due, apft due, next eval due.  This also sounds like a complicated worm hole

**Comment by mattgwagner** [comment]
I ended up handling this when selecting the add evaluation for Soldier from the evaluations list by looking at the last one in the system.
